partage_experience_homepage:
    path:     /
    defaults: { _controller: PartageExperienceBundle:Avis:Avis }

Ajout:
    path:     /Ajout
    defaults: { _controller: PartageExperienceBundle:Avis:AjouterAvis }

List:
    path:     /List
    defaults: { _controller: PartageExperienceBundle:Avis:ListAvis }

Modifier:
    path:     /Modifier
    defaults: { _controller: PartageExperienceBundle:Avis:ModifierPartage }

Supprimer:
    path:     /Supprimer/{idPartageH}
    defaults: { _controller: PartageExperienceBundle:Avis:SupprimerPartage }

Contact:
    path:     /Contact
    defaults: { _controller: PartageExperienceBundle:Contact:Contact }

recherche_ajax:
    path:     /recherche_ajax
    defaults: { _controller: PartageExperienceBundle:Avis:rechercheAjax }